# docker-compose.yml
version: "3"
services:
  app:
    build: .
    container_name: New-System-Node
    volumes:
      - .:/home/app/
      - /home/app/node_modules
      - /home/app/node_js
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"

  postgres:
    image: postgres:11.2-alpine
    container_name: New-System-Postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      -  "5432:5432"
